import os

API_KEY = os.getenv("API_KEY")

#os.getenv("COSMOSDB_CONNECTIONSTRING")
COSMOSDB_CONNECTIONSTRING = "AccountEndpoint=https://vshunger2020.documents.azure.com:443/;AccountKey=MeZdteQmRLtFQUgqnzUmynLdfGPk28w12rqIICgdC9CGpQOrvECLKHATOavHrH0gRl93RjLXDPQNLlDswhlNeg=="
COSMOSDB_ENDPOINT, COSMOSDB_API_KEY = COSMOSDB_CONNECTIONSTRING.split(";")
COSMOSDB_ENDPOINT = COSMOSDB_ENDPOINT[COSMOSDB_ENDPOINT.find("=") + 1:]
COSMOSDB_API_KEY = COSMOSDB_API_KEY[COSMOSDB_API_KEY.find("=") + 1:]

DB_NAME = "vshunger2020"
BASE_FUNDRAISER_ID = "GoldfishVsHunger2020-"